services:
  sunec_backend:
    container_name: sunec_backend
    image: ghcr.io/fastschema/fastschema:latest
    ports:
      - '8000:8000'
    restart: always
    volumes:
      - ./backend/data:/fastschema/data
    env_file:
      - ./backend/.env
  sunec_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: sunec_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '8080:8080'
    command: sh -c "pnpm install && pnpm dev"
    env_file:
      - ./frontend/.env
    links:
      - sunec_backend
