services:
  packtech_backend:
    container_name: packtech_backend
    image: ghcr.io/fastschema/fastschema:latest
    ports:
      - '8000:8000'
    restart: always
    volumes:
      - ./backend/data:/fastschema/data
    env_file:
      - ./backend/.env
  packtech_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: packtech_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    command: sh -c "npm install --legacy-peer-deps && npm run dev"
    env_file:
      - ./frontend/.env
    links:
      - packtech_backend
